[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "lilota"
version = "0.1.0"
authors = [
  { name="Tobias RÃ¶ssler", email="tobiasroessler@gmail.com" },
]
dependencies = [
  "SQLAlchemy>=2.0",
  "alembic>=1.17"
]
description = "A lightweight solution for long-running tasks"
readme = "README.md"
requires-python = ">=3.12"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[tool.setuptools.packages.find]
where = ["."]
exclude = ["tests*"]

[tool.setuptools.package-data]
"lilota" = ["db/migrations/**", "db/migrations/**/**"]

[project.urls]
Homepage = "https://github.com/tobiasroessler/lilota"
Issues = "https://github.com/tobiasroessler/lilota/issues"